---
image: patwoz/expo-cli:3

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - publish

before_script:
  - yarn install --pure-lockfile --non-interactive

publishing:
  stage: publish
  script:
    - echo "IP_ADDRESS=$IP_ADDRESS MAPS_API_KEY=$MAPS_API_KEY apiKey=$apiKey authDomain=$authDomain projectId=$projectId facebookId=$facebookId googleIosClientId=$googleIosClientId googleAndroidClientId=$googleAndroidClientId" >> .env
    - cat .env
    - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
    - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - expo publish --release-channel prod --non-interactive
  only:
    - master
    - ci-publishing
