---
image: node:alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - publish

before_script:
  - yarn install --pure-lockfile --non-interactive

publishing:
  stage: publish
  script:
    - cd app
    - yarn expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - yarn expo publish --release-channel prod --non-interactive
  only:
    - master
    - ci-publishing
