---
image: patwoz/expo-cli:3

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - publish
  - staging

before_script:
  - cd app
  - cat $GOOGLE_CONFIG > .google-services.json
  - cat $FIREBASE_CONFIG > ./src/config/authmiaajuda-firebase.json
  - yarn install --pure-lockfile --non-interactive

publishing:
  stage: publish
  script:
    - chmod +x ./setup_env.sh
    - ./setup_env.sh
    - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
    - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - expo publish --release-channel prod --non-interactive
  only:
    - master

staging:
  stage: staging
  script:
    - chmod +x ./setup_env.sh
    - ./setup_env.sh
    - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
    - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - expo publish --release-channel staging --non-interactive
  only:
    - develop
